name: carto
description: A modern shopping app UI prototype
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Manejo de imágenes desde dispositivo
  image_picker: ^1.0.7

  # Gestión de permisos
  permission_handler: ^11.3.0

  # Gestión de estado
  provider: ^6.1.2

  # Base de datos local
  sqflite: ^2.3.0
  path: ^1.8.3

  dashed_border: ^1.0.2

  # Almacenamiento local
  shared_preferences: ^2.2.0

  # Iconos iOS
  cupertino_icons: ^1.0.8

  # Fuentes Google
  google_fonts: ^7.1.0

  # SVG
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/products.json