name: carto
description: "A modern shopping app UI prototype"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # Iconos iOS / Material
  cupertino_icons: ^1.0.8

  # Fuentes modernas (Inter, etc.)
  google_fonts: ^6.1.0

  # SVG support (por si luego usas Ã­conos vectoriales)
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
